### ISSUE TITLE
[BUG] Character expressions invisible on PC WaifuMode (1.4.0)

### ISSUE THREAD

**Issue by TheWandering514** [Cohee1207/SillyTavern#124]
**Describe the bug**
Character expressions "appear", but are invisible to the user in PC WaifuMode on SillyTavern release 1.4.0

**To Reproduce**
1. Download SillyTavern release 1.4.0
2. Launch SillyTavern locally on Windows using start.bat
3. Go to the SillyTavern site in browser, ensure WaifuMode is enabled, and preview a character expression in offline mode. Can test multiple character expressions to be doubly sure.
4. Character expression does not appear as expected, but it is possible to right click in the area where they should be to open the image in a new tab.
5. Disabling WaifuMode will make the sprite reappear to the left of the chat window.

**Expected behavior**
Character expression should be visible when previewing them. This had been working on the previous dev version I have on my PC, which was downloaded around commit b13b1dc.

**Screenshots**
Screenshot showing the bug as well as inspecting element to show that the image element is there, but just invisible
![image](https://user-images.githubusercontent.com/130191619/233529252-596d4495-8862-4410-a6ac-0f3249a09587.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Environment: Locally hosted SillyTavern
 - Browser Opera, Chrome
 - Generation API: N/A for this bug
 - Branch: Main, but the 1.4.0 release download specifically
 - Model: N/A for this bug

**Comment by RossAscends** [comment]
not possible to bugcheck this unless we have the PNG file itself. 

try turning on default sprites, removing your custom sprites from their usual location, and checking it the default expression sprites load.

**Comment by TheWandering514** [comment]
> I was able to reproduce it with the character background plugin lock engaged. Fixed in main [4f14557](https://github.com/Cohee1207/SillyTavern/commit/4f145570111ac115bc7abb4004e5df4c7aa2d4be)

Pulled main, and while the sprites aren't invisible anymore, it seems now that half-bodied sprites are cut off from the bottom by default - irrespective of whether they have been cropped or are in a 16:9 aspect ratio.

**Example of full-bodied sprite, showing that the invisibility bug is now fixed on my end:**
![image](https://user-images.githubusercontent.com/130191619/233688605-f358040a-0568-4861-9611-885e63bbfc1e.png)

**Example of half-bodied sprite that's cut off from the bottom:**
![image](https://user-images.githubusercontent.com/130191619/233688488-55ae8b31-ec46-4c7b-8954-1791c2530c34.png)
I tried using movable UIs, and it doesn't seem like I can drag the sprite down myself despite there being an indication that I can - all it does is highlight the expression holder.
![image](https://user-images.githubusercontent.com/130191619/233690019-f20f1a32-3971-4e35-beef-824c69fb061c.png)
However, I do think it would be troublesome having to readjust the sprites to not be cut off every time.




If you want to try reproducing my results, here's the exact character card and sprites I used for the earlier screenshots:
![Lemon](https://user-images.githubusercontent.com/130191619/233688865-e7ecaef2-4e2f-4716-8065-19174291a8ff.png)
[Lemon.zip](https://github.com/Cohee1207/SillyTavern/files/11297631/Lemon.zip)

**Comment by TheWandering514** [comment]
> @TheWandering514 try on dev branch after this commit [dfe3801](https://github.com/Cohee1207/SillyTavern/commit/dfe3801f79a2e3b6c59c4ca5edb48eb101b697e0)

Pulled the dev branch and can confirm it being fixed, I think I can close this issue now. Thanks for the fix.
