### ISSUE TITLE
[BUG] Cannot scroll all the way to the top of dialogue on mobile WaifuMode with Character Bots with more verbose intros

### ISSUE THREAD

**Issue by TheWandering514** [Cohee1207/SillyTavern#125]
**Describe the bug**
It is not possible to scroll to the top of dialogue on mobile WaifuMode when talking to Character Bots with more verbose introductions. The problem already manifests from the very first message by the character, and persists even with multiple exchanges.

**To Reproduce**
1. Pull the latest version on Main (or commit c702145, the version I'm at right now) on Android Termux
2. Launch SillyTavern locally on Android Termux
3. Go to the SillyTavern site on mobile device and enable WaifuMode
4. Choose a character bot with a more verbose introduction, around 10+ lines long? Alternatively, download the same character card I used in my recording in **Additional Context**
5. Already impossible to scroll up to see the beginning of the introduction dialogue after loading the character fresh
6. Can attempt further exchanges with the bot, but it still isn't possible to scroll up to the very top of the dialogue

**Expected behavior**
The chat window should allow the user to scroll up to the very top of the dialogue, allowing them to see the entirety of the introductory greeting for referencing.

**Screenshots**
Video footage of the bug in action taken from Android, with the SillyTavern site added to homescreen via Chrome:

https://user-images.githubusercontent.com/130191619/233534642-9fa5dca5-0cc9-4f15-800d-93c3d425d931.mp4

**Desktop (please complete the following information):**
 - OS: Android
 - Environment: Locally hosted SillyTavern
 - Browser Chrome, but SillyTavern added to homescreen
 - Generation API: N/A for this bug
 - Branch: Main, specific commit c702145
 - Model: N/A for this bug

**Additional context**
The character card I was using for the footage (metadata should be preserved despite the borked filename)
![Ferrari-Chan](https://user-images.githubusercontent.com/130191619/233534850-97d46a0c-5583-44f3-86c4-0c5845765f0a.png)

**Comment by RossAscends** [comment]
what OS version? This problem does not exist on iOS or in the PC Chrome's simulation of a mobile device.

**Comment by RossAscends** [comment]
Ok fixed and pushed to the dev branch. Please update your install.

**Comment by TheWandering514** [comment]
> Ok fixed and pushed to the dev branch. Please update your install.

Pulled latest Dev and can confirm it has been fixed, thank you once again - I'll close this issue now.
