### ISSUE TITLE
When I go back to the first message with swiping the generated response is always replaced with "..."

### ISSUE THREAD

**Issue by PortalTom** [Cohee1207/SillyTavern#138]
Is there any way to fix the above or is it just a bug with the current sysyem?
I can go back to the second or third message just fine, but if I go back to the first one it's always replaced with: "..."

**Comment by RossAscends** [comment]
Are you using a streaming API when this happens?

**Comment by PortalTom** [comment]
> Are you using a streaming API when this happens?

I'm using the oobabooga api if that's what you mean.

**Comment by RossAscends** [comment]
this has been fixed. please update.
