### ISSUE TITLE
[BUG] Elevenlabs extension ignores voice settings

### ISSUE THREAD

**Issue by minipasila** [Cohee1207/SillyTavern#140]
**Describe the bug**
The voices differ greatly when you use them on SillyTavern vs when you use them natively on Elevenlabs.

**To Reproduce**
1. Add an Elevenlabs voice.
2. Generate a new response.

**Expected behavior**
It should use the same settings from Elevenlabs, so the voice would be the same.

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Browser: Firefox
 - Generation API: OpenAI
 - Branch: dev
 - Model: gpt-3.5-turbo-0301

**Comment by ouoertheo** [comment]
I sure can. I'll squeeze that in between weekend activities.

**Comment by ouoertheo** [comment]
There's a PR including the feature to control the settings on generation for 11labs up for review.

**Comment by minipasila** [comment]
![image](https://user-images.githubusercontent.com/4912958/233863164-ce57859e-7cd5-4d8f-ac18-8eda702bf6a0.png)
are these the same setting? (also let me use numbers like 0,23 etc. as it's on elevenlabs)
also i guess i need to manually remove the old extension

**Comment by ouoertheo** [comment]
Whoops, copypasta gone wrong.... glad it worked for you.
