### ISSUE TITLE
How do I make the generated text gradually appear like it used to?

### ISSUE THREAD

**Issue by PortalTom** [Cohee1207/SillyTavern#161]
As the title says, I'm curious what setting I need to adjust to watch the text generate in my ui instead of having to wait for the whole thing to see any of it.

**Comment by pseudograph** [comment]
Check "streaming" in the AI Response Configuration menu. It sometimes gets stuck while streaming text though, so I don't use it.

**Comment by PortalTom** [comment]
> Please provide full information using the recommended template.

The bug is that the text appears all at once instead of gradually appearing.

To reproduce send a message to the bot.

Expected behavior is that the text gradually appears like it used to.

OS is windows 11 local browser is chrome generation api is oobabooga branch is main and model is pygmalion 6b

**Comment by PortalTom** [comment]
I would also like to know this. I thought I clicked the right box, but it still won't gradually generate.

**Comment by PortalTom** [comment]
> Where is that option?

I would also like to know this. I thought I clicked the right box, but it still won't gradually generate.

**Comment by RossAscends** [comment]
Template needs updating, apparently. 

What API are you trying to use to get the 'gradual text' (technically called 'streaming')?

**Comment by PortalTom** [comment]
> Template needs updating, apparently.
> 
> What API are you trying to use to get the 'gradual text' (technically called 'streaming')?

I'm ussing the latest version of oobabooga as my api.

**Comment by RossAscends** [comment]
That is the problem. oobabooga changed their API (again) yesterday to be two different ports. one for normal generation, and one for streaming. we have attempted to resolve this in SillyTavern, but have not been able to yet.

**Comment by PortalTom** [comment]
> That is the problem. oobabooga changed their API (again) yesterday to be two different ports. one for normal generation, and one for streaming. we have attempted to resolve this in SillyTavern, but have not been able to yet.

Oh I see, do you know if kobold ai still works for streaming with sillytavern?

**Comment by PortalTom** [comment]
I updated oobabooga and it works again now for some reason.
Have no idea why.
