### ISSUE TITLE
[BUG?] Quotation marks can't be copied

### ISSUE THREAD

**Issue by R18C188** [Cohee1207/SillyTavern#202]
**Describe the bug**
Since the dev update allowing adjustment of quote text color separately, copying the quotes themselves has become impossible. Of course I can copy raw text, but that's too cumbersome, and I have to manually remove other markdowns if I do that.

Alternatively I could manually add the quotation marks to the copied text, but as you can imagine, that's also too cumbersome.

As an ESL this issue is significant. Not using quotes is not viable, as it greatly affects translation quality. Please help

**To Reproduce**
Copy the quoted text

**Expected behavior**
Copiable quotes

**Desktop (please complete the following information):**
Win11, local, latest chrome and firefox, dev branch

**Comment by RossAscends** [comment]
Checked this, and will clarify the problem: 

The new quotes display makes copying the quotation characters themselves impossible.

example: 

`"What a nice day for a walk", the man said.`

would become copied as: 

`What a nice day for a walk, the man said.`

**Comment by RossAscends** [comment]
this has now been fixed in dev branch.

**Comment by R18C188** [comment]
You saved my soul thanks
