### ISSUE TITLE
[BUG] #sheld element isn't always aligned with the #top-bar element

### ISSUE THREAD

**Issue by kaiio14** [Cohee1207/SillyTavern#206]
**Describe the bug**
The main content of the chat window is shifted to the right compared to the top bar. This is caused when the screen height isn't a whole number. Then in `index.html` `window.innerHeight` may round the number up when assigning it to `--doc-height`. Then the body of the document technically becomes longer than the screen, causing a scrollbar to appear on the right, and this displaces the #top-bar element, while #sheld stays in place because of its absolute positioning.

The screen height may become a non-whole number when the scale of the Windows layout is increased to make content more readable on devices with high resolution.

**To Reproduce**
1. Zoom in or zoom out with your browser until the screen height includes a decimal point. On Chrome it can be done with `ctrl +` or `ctrl -`
2. In windowed mode, resize the browser window vertically.
3. You will see the background and the #top-bar element flickering as the scroll-bar appears and disappears.

**Expected behavior**
The #top-bar element and the #sheld element should be always aligned.

**Screenshots**
![Screenshot 2023-04-30 105924](https://user-images.githubusercontent.com/125736993/235342557-6b8a58be-4894-40b6-95f5-c00b084a96ad.png)

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: local
 - Browser: chrome
 - Generation API: Oobabooga web ui
 - Branch: main
 - Model: WizardLM 7b

**Comment by RossAscends** [comment]
able to reproduce, looking into it.

**Comment by RossAscends** [comment]
I pushed what I think is a fix for this on dev branch. Check and let me know if your problem persists.

**Comment by kaiio14** [comment]
Now the difference is down to 1 pixel, likely because the two elements use different centering methods. The #sheld element having `left: 0; right: 0; margin: 0 auto;` seems to work.

**Comment by RossAscends** [comment]
pushed with that change, and removed the -1px width adjustment for body. i don't see any misalignments on my end (can only test up to 175% zoom on 1080p before it jumps over to mobile UI display)

 let me know if this works for you.
