### ISSUE TITLE
[Feature Request] Buttons to decide who speaks next in group chat

### ISSUE THREAD

**Issue by m957ymj75urz** [Cohee1207/SillyTavern#224]
**Is your feature request related to a problem? Please describe.**
The group chat feature is awesome but, unless I am missing something, there is no way to decide who will be the next one to speak. In simple setup the natural order with the Shy - Chatty slider might be enough but I would love a way to precisely decide who is the next character to talk.

**Describe the solution you'd like**
A button in the group chat interface to trigger a specific character answer. Could be also nice to add a third choice to the group reply strategy called "None", where no one will ever talk by themselves (but I guess setting all character to Shy would have the same result)

**Describe alternatives you've considered**
For now, I send `[Game Master]` to trigger a reply, it works, but it feels wonky and also costs tokens.

**Additional context**
For example, right now, I have a group chat with my adventurers and a Game Master. I don't want the game master to drive the adventure too fast by interrupting our talks while we decide how to proceed trough the dungeon.

**Comment by VanguardDawn** [comment]
I just came here to make this request, though Cohee's solution does work fine. I feel like it would be a lot more intuitive to have a button that does it automatically.

**Comment by olamedia** [comment]
I would like to trigger Narrator instead of characters at some time. And a "skip" button to skip user's prompt.

**Comment by VanguardDawn** [comment]
What a legend. It's looking great.
