### ISSUE TITLE
[BUG] Making a group is broken on mobile latest dev update

### ISSUE THREAD

**Issue by Zer0PXL** [Cohee1207/SillyTavern#248]
**Describe the bug**
Trying to make a group is impossible. You can't add any characters and the UI is bugged.

**To Reproduce**
1. Start SillyTavern
2. Attempt to create a group
3. See error

**Expected behavior**
What I saw in the older versions.

**Screenshots**
![Screenshot_20230506_204237_Kiwi Browser](https://user-images.githubusercontent.com/84981290/236639194-556630e0-2a3c-46fa-82f7-74fd20ee4cb2.jpg)

**Mobile (please complete the following information):**
 - OS/Device: [e.g. Windows 11] Android 13
 - Environment: [cloud, local] local
 - Browser [e.g. chrome, safari] Kiwi Browser (Chromium)
 - Generation API [e.g. KoboldAI, OpenAI] Poe
 - Branch [main, dev] dev
 - Model [e.g. Pygmalion 6b, LLaMa 13b] (idk for Poe)

**Comment by RossAscends** [comment]
The new group layout was tested on Safari, Chrome, and Firefox, and Brave browser on iOS. All display it correctly. 

Is your Kiwi browser up to date?

**Comment by Zer0PXL** [comment]
The browser is up to date.

**Comment by Zer0PXL** [comment]
I pulled the latest update and it got fixed...updates on the dev branch come out faster than you can make an issue lok

**Comment by Zer0PXL** [comment]
Fixed in unknown update
