### ISSUE TITLE
[BUG] TTS Settings Tab is missing

### ISSUE THREAD

**Issue by gzt567** [Cohee1207/SillyTavern#297]
**Describe the bug**
TTS Settings Tab is missing in Silly Tavern 1.5.1 Extensions UI.

**To Reproduce**
1. I installed and uptodated Silly Tavern AI as instructed to try out the new TTS options of v1.5.1
2. Then I installed the Silly Tavern Extras like instructed here: https://github.com/Cohee1207/SillyTavern-extras
(I changed requirements.txt to requirements-complete.txt)
3. When it says to use th following line "python server.py --enable-modules=caption,summarize,classify" I did add the "tts" so it looks like this "python server.py --enable-modules=caption,summarize,classify,tts"

**Expected behavior**
The Silly Tavern Extensions Interface should show the Settings for TTS like shown here:
![grafik](https://github.com/Cohee1207/SillyTavern/assets/130252724/f84ae734-8282-4c80-93b8-9c9766bbb395)

Everything looks fine, when Python is loading the extensions:

```
Initializing an image captioning model...
Initializing a text summarization model...
Initializing a sentiment classification pipeline...
Initializing Silero TTS server
2023-05-13 15:32:01.236 | INFO     | silero_api_server.tts:__init__:38 - TTS Service loaded successfully
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5100
```

Silly Tavern also tells me, that everything should work:
![grafik](https://github.com/Cohee1207/SillyTavern/assets/130252724/d576cafa-2fa7-49d6-aa01-cf98e4d9f19c)

**Screenshots**
This is how it look with my Silly Tavern UI; the TTS Settings are missing:
![grafik](https://github.com/Cohee1207/SillyTavern/assets/130252724/ab59d617-bbe6-4989-a623-0fe689dba546)

**Desktop (please complete the following information):**
 - OS/Device: [e.g. Windows 10]
 - Environment: [local]
 - Browser [e.g. chrome, firefox,brave]
 - Generation API [e.g. KoboldAI]

**Comment by gzt567** [comment]
> Wasn't able to reproduce on my end. Missing plugin in a list means it could not be loaded due to an error. Try opening the DevTools and see the reason.

Thank you for testing it! How do I open the Dev Tools? Sorry, just starting out with everything here...

**Comment by sanskar-mk2** [comment]
https://www.google.com/search?q=How+do+I+open+the+Dev+Tools

**Comment by gzt567** [comment]
Okay, thx, I thought you meant a dev tool in Silly Tavern. So, I could solve it by installing it again and suddenly it worked. Thanks for your help!
