### ISSUE TITLE
[BUG] Poe Socket Connection Timeout

### ISSUE THREAD

**Issue by KeystrokeCascade** [Cohee1207/SillyTavern#306]
**Describe the bug**
Just set up ST cloning from the main branch onto my Ubuntu server, after trying to add the Poe API key it hangs after or during downloading Dragonfly with a socket connection timeout error.

**To Reproduce**
1. Follow the Poe API instructions in `localhost:8000/notes/#apikey-2`
2. Look in CLI

**Logs**
```
Downloading next_data...
Downloading channel data...
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/Sage.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/GPT-4.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/Claude+.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/Claude-instant-100k.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/Claude-instant.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/ChatGPT.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/NeevaAI.json
Downloading https://poe.com/_next/data/zSW0YByCbb5zxL0aTWmjf/Dragonfly.json
Websocket returned error: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
```

**Desktop (please complete the following information):**
 - OS/Device: Arch Linux (laptop)/Ubuntu 22.04.2 LTS 
 - Environment: Local server
 - Browser: Firefox
 - Generation API: Poe
 - Branch: Main
 - Model: Claude-Instant

**Comment by KeystrokeCascade** [comment]
v20.1.0, I just used the nvm the script installed.

**Comment by RossAscends** [comment]
NodeJS v20 gives us problems. Use nodeJS LTS v18.15 or 18.15

**Comment by KeystrokeCascade** [comment]
Setting nvm to v18.15 LTS worked!  Would there be some way to set that automatically with the start.sh script?  Could be useful for avoiding issues like this in the future until v20 stops having problems.
