### ISSUE TITLE
[Feature Request] Multiple Jailbreaks

### ISSUE THREAD

**Issue by sanskar-mk2** [Cohee1207/SillyTavern#325]
**Is your feature request related to a problem? Please describe.**
It is known that different jailbreaks works well with different cards. Sometimes you want paragraph RP, but sometimes you want some stats to display and so on. Right now, there is no ability to swap jailbreaks on the fly. If I change my jailbreak, I lose the last one that I want to use on other cards.

**Describe the solution you'd like**
A dropdown of Jailbreaks, you can add, delete and edit any number of jailbreaks you want. You can select whichever you want from them.

**Describe alternatives you've considered**
Author's note/Character Bias. But it is not convenient to try out a JB in multiple chats to see how it fares.

**Additional context**
It can be something like logit bias dropdown (but with textboxes instead of multiple checkboxes) where we can create multiple JB and choose whichever you want.

**Comment by RossAscends** [comment]
Jailbreak is not the place to actively modify behavior. The purpose of the jailbreak is to allow the AI to ignore restrictions and training bias. 

If you want to actively modify the AI's response behavior, there are MANY ways to do this: 

- character definitions
- world info
- authors note 
- character nudge 
- {{}} commands.
