### ISSUE TITLE
[BUG] Streaming Oobabooga breaks emojis

### ISSUE THREAD

**Issue by minipasila** [Cohee1207/SillyTavern#354]
**Have you searched for similar [bugs](https://github.com/Cohee1207/SillyTavern/issues?q=)?**
Yes

**Describe the bug**
When you enable streaming for Oobabooga, it breaks the emojis and generates this instead "���", and when you disable streaming, it generates the emotes as if nothing was ever wrong.

**To Reproduce**
1. Connect to Oobabooga's UI
2. Enable streaming from the settings.
3. Ask the AI to generate emotes.
4. See the error as explained above.

**Expected behavior**
It should show the emotes correctly.

**Screenshots**
Streaming disabled:
![image](https://github.com/Cohee1207/SillyTavern/assets/4912958/70f2212b-a14b-40d6-81ce-c352e1b88753)
Streaming enabled:
![image](https://github.com/Cohee1207/SillyTavern/assets/4912958/18973fd2-446f-464b-9fb9-382264897983)

**Logs**
```
{
  prompt: "Write ChatGPT's next reply in a fictional roleplay chat between Minipasila and ChatGPT.\n" +
    '\n' +
    'ChatGPT is a helpful AI assistant.\n' +
    '\n' +
    '\n' +
    '\n' +
    'Then the roleplay chat between Minipasila and ChatGPT begins.\n' +
    '### Response:\n' +
    "ChatGPT: Hello I'm ChatGPT and I will try my best to help you.\n" +
    '</s>Minipasila: can you use some emojis?\n' +
    '\n' +
    '\n' +
    '### Response:\n' +
    'ChatGPT:',
  max_new_tokens: 512,
  do_sample: true,
  temperature: 0.5,
  top_p: 0.9,
  typical_p: 1,
  repetition_penalty: 1.1,
  encoder_repetition_penalty: 1,
  top_k: 0,
  min_length: 0,
  no_repeat_ngram_size: 0,
  num_beams: 1,
  penalty_alpha: 0,
  length_penalty: 1,
  early_stopping: false,
  seed: -1,
  add_bos_token: false,
  stopping_strings: [ '\nYou:', '\nMinipasila:', '\n### Response:' ],
  truncation_length: 2048,
  ban_eos_token: false,
  skip_special_tokens: true
}
#### {
  results: [
    {
      text: ' Sure, here are some emojis for you: 😊, 🤩, 💖, 🧁, 🦉, 🐶, 🍀, 🎂, 🎁, 🎉, 🎆, 🌈, 💥, 🔪, 🚫, 👹, 👹, 👺, 👻, 💃, 🎶, 🏋️‍, 💨, 🛁, 💩, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢,
🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, '
    }
  ]
}
{
  results: [
    {
      text: ' Sure, here are some emojis for you: 😊, 🤩, 💖, 🧁, 🦉, 🐶, 🍀, 🎂, 🎁, 🎉, 🎆, 🌈, 💥, 🔪, 🚫, 👹, 👹, 👺, 👻, 💃, 🎶, 🏋️‍, 💨, 🛁, 💩, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢,
🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, 🤢, '
    }
  ]
}
{
  prompt: "Write ChatGPT's next reply in a fictional roleplay chat between Minipasila and ChatGPT.\n" +
    '\n' +
    'ChatGPT is a helpful AI assistant.\n' +
    '\n' +
    '\n' +
    '\n' +
    'Then the roleplay chat between Minipasila and ChatGPT begins.\n' +
    '### Response:\n' +
    "ChatGPT: Hello I'm ChatGPT and I will try my best to help you.\n" +
    '</s>Minipasila: can you use some emojis?\n' +
    '\n' +
    '\n' +
    '### Response:\n' +
    'ChatGPT:',
  max_new_tokens: 512,
  do_sample: true,
  temperature: 0.5,
  top_p: 0.9,
  typical_p: 1,
  repetition_penalty: 1.1,
  encoder_repetition_penalty: 1,
  top_k: 0,
  min_length: 0,
  no_repeat_ngram_size: 0,
  num_beams: 1,
  penalty_alpha: 0,
  length_penalty: 1,
  early_stopping: false,
  seed: -1,
  add_bos_token: false,
  stopping_strings: [ '\nYou:', '\nMinipasila:', '\n### Response:' ],
  truncation_length: 2048,
  ban_eos_token: false,
  skip_special_tokens: true
}
websocket open
 Sure, here are some emojis for you: �������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������


```

**Desktop (please complete the following information):**
 - OS/Device: Windows 11
 - Environment: local
 - Node.js version (if applicable): v18.12.1
 - Browser: Firefox
 - Generation API: Oobabooga's text-generation-webui
 - Branch: dev
 - Model: TheBloke/Wizard-Vicuna-7B-Uncensored-GPTQ

**Additional context**
Nothing really. Other than that I have it installed on an anaconda environment.

**Comment by minipasila** [comment]
I hadn't tried the API itself since in the webui itself it worked fine in streaming. But yeah I'll do that.

**Comment by keturn** [comment]
Some models — I'm seeing this on [https://huggingface.co/brucethemoose/Yi-34B-200K-DARE-megamerge-v8](brucethemoose/Yi-34B-200K-DARE-megamerge-v8) at the moment — seem to be encoding emoji as UTF-8 byte sequences:
> - <0xF0><0x9F><0xA4><0xA3> Rolling on the Floor Laughing

If the role of the streaming API is to return each token as it comes, then it's doing its job here. If the individual tokens aren't Unicode codepoints, well, that's a choice a tokenizer can make and it's not the API server's fault the model works that way.

In which case, it's the client's responsibility to figure out "hey, <0xF0> is the start of a longer UTF-8 sequence" and then after the sequence completes, do `b'\xF0\x9F\xA4\xA3'.decode('utf-8')`  to get the unicode out. (It looks like [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) or perhaps `TextDecoderStream` is what could do that for you in JavaScript.)

…the caveat being that the model may produce invalid UTF-8 byte sequences, just as it may or may not follow any other syntax in its output, so the decoder needs some fallback option when things get messy.

**Comment by Cohee1207** [comment]
Text Generation WebUI doesn't return the decoded token if the output is not a valid Unicode character, i.e. if the decoded token produces a character replacement symbol - it buffers it with the next token. It worked flawlessly so far since the resolution of this issue. I can't agree that it's more of a frontend job to do sequential decoding as I'd expect the backend to produce only usable text in the output.
