### ISSUE TITLE
[BUG] Cannot scroll on iOS mobile

### ISSUE THREAD

**Issue by rahoyo** [Cohee1207/SillyTavern#46]
**Describe the bug**
On iPad everything works, but on iPhone XS Max I am unable to scroll through chats in portrait mode (with or without full screen). In landscape on iPhone, scrolling works.

**To Reproduce**
1. Go to local IP on iPhone
2. Can browse menus and chats, but there is no scroll bar or ability to scroll through chat conversations while in portrait mode.

**Expected behavior**
Expect to be able to scroll normally in portrait on iPhone.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS/Device: [iPhone XS Max, iOS 14]
 - Environment: [local]
 - Browser [Safari]
 - Generation API [Text generation web UI] 
 - Branch [main]
 - Model [Pygmalion 6b]

**Additional context**
Tried adding `<meta name="viewport" content="width=device-width, initial-scale=1">` to index.html, but did not help.

**Comment by RossAscends** [comment]
Currently main branch's mobile ui is optimized for android. Dev branch has a working ui for iOS which respects the safe area. Switch to dev branch to get this now, or wait until it is added to main branch.

**Comment by rahoyo** [comment]
Thanks. After switching to the updated dev branch, the mobile UI menu bar looks different (all the buttons are left aligned, doesn't really matter), but none of the buttons work (no menus open). That is on the iPhone XS Max screen, but the iPad still works normally.

**Comment by RossAscends** [comment]
I am unable to replicate the completely non-working buttons on my end. They are a bit finicky to touch though due to their size.

**Comment by RossAscends** [comment]
Also check your iOS version. The XS Max is 5 years old now and may not have the version support required to make our iOS UI trigger properly.

**Comment by rahoyo** [comment]
Thanks for checking. I don't want to update from iOS 14 and lose my jailbreak, and the iPad is also on iOS 14 and works normally. I thought it might have something to do with screen size, but I understand if you can't investigate on the older software.

If it helps at all, before the recent SillyTavern update when the dependencies were fixed, the mobile UI menus worked except for scrolling in the chat itself. Something that changed from the SillyTavern version available last week seems to have caused the menu bar issue. Here is a [screenshot.](https://i.imgur.com/1YM0WFW.jpeg) On the iPhone XS Max, the page is unresponsive (can't pinch to zoom, buttons highlight but don't do anything). All other websites work normally.

Anyways, thanks for working on this amazing software, I really love it.

Also, a few quick questions:
-Is it possible to run SillyTavern on Linux, or is everything including the extensions for Windows only?
-Is it possible to have a live text feedback, like how chatGPT responds?

**Comment by RossAscends** [comment]
Recent updates to default (non-iOS) mobile ui should have fixed this. Please update and try again. Reopen if you still see problems.
