### ISSUE TITLE
Allow left and right menus (presets and characters) to overlap the message space

### ISSUE THREAD

**Issue by jojobear13** [Cohee1207/SillyTavern#48]
**Is your feature request related to a problem? Please describe.**
Prior to commit 0c8f068a8a5a58296c777ddaee0e4e07bf85dd65, the character menu was allowed to overlap the message area like so:
<img width="956" alt="Capture1b" src="https://user-images.githubusercontent.com/47074297/230822565-7e8d4fea-692d-44f5-9cb7-88a830652094.PNG">

Commit 0c8f068a8a5a58296c777ddaee0e4e07bf85dd65 changed it so that this menu will not overlap the text area. Furthermore, the presets menu us now similarly locked to the margin left of the text area.

The problem I have is that now these two menus get squished and are very annoying to use because they are not allowed to overlap the message area anymore. See below for my experience (locks were activated just for taking the screenshot).

<img width="955" alt="Capture2" src="https://user-images.githubusercontent.com/47074297/230821983-4045a92c-6fa5-4878-843c-534e76ff7b4e.PNG">

**Describe the solution you'd like**
Please allow these menus to overlap like before prior to 0c8f068a8a5a58296c777ddaee0e4e07bf85dd65 

**Describe alternatives you've considered**
I can zoom-out my browser to increase the size of the menus, but this reduces the size of the font for the whole UI and makes things hard to read. My eyes are not very good, and I typically need 120% or more zoom.

**Comment by RossAscends** [comment]
The purpose of preventing the left and right panels from overflowing chat display is to allow users to use them while chatting to tweak their generation settings and character definitions. 

The correct way to fix this would be to increase the font size, not alter the entire site's display paradigm.

Altering font sizes via UI is an upcoming feature. 

Until then you can alter the font size manually in the style.css file. Near the top of the file (currently line 68) you will
See "font-size: 15px;". 

Change that to whatever you feel is comfortable. Recommend not going over 18px as it can cause UI-breaking largeness.

**Comment by jojobear13** [comment]
This helps with the readability of the main text, but the new fixed layout is still overly restrictive. On the character descriptions, all the text is crammed into a tight column, and I have to zoom the UI out to 80% if I want things to look legible while I'm reading or editing it (which in turn makes the text smaller).

There are also other side effects to this change:
- Unlocking the left and right menus leaves large blank areas on the side (assuming no extensions).
- Toggling the message window to 1000 pixels to fill the blank sides now makes the side menus so skinny as to be unreadable.

Proposal: The "unlock" status should allow the menus to overlap like before. The "lock" status restricts them to the area.

**Comment by RossAscends** [comment]
We added a font slider on dev branch. This should solve your issue.
