### ISSUE TITLE
[BUG] Cannot scroll on Android Chrome 

### ISSUE THREAD

**Issue by Gab991210** [Cohee1207/SillyTavern#52]
Cannot scroll on Android Chrome 
(Google Pixel 6, Android 13) 
Using Termux (Open AI API), everything works fine except scrolling up and down. 
Thanks.
![Screenshot_20230410-205326](https://user-images.githubusercontent.com/69129039/231034454-70347c17-b355-4ede-8494-64339f5bd326.png)

**Comment by RossAscends** [comment]
Thank you for the update. I've incorporated the necessary parts of your css into the dev branch css. Please pull and let me know if it works.
