### ISSUE TITLE
[Feature Request] Allow Pyg to disable "Always add character's name to prompt"

### ISSUE THREAD

**Issue by cass02** [Cohee1207/SillyTavern#70]
**Describe the bug**

When `Always add character's name to prompt` is disabled, the character's name is still prepended in the prompt.

**To Reproduce**

1. Disable `Always add character's name to prompt`
2. Generate
3. View context in terminal

**Expected behavior**

The character's name should not be prepended in the prompt.

**Screenshots**

Character's name is `DEBUG:` and `Always add character's name to prompt` was disabled:

![screenshot](https://i.gyazo.com/cd087d141f4569ab3352132d28cb8f60.png)

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: Local
 - Browser: Chrome
 - Generation API: KoboldAI
 - Branch: Dev
 - Model: Pygmalion 6B

**Comment by cass02** [comment]
**Is your feature request related to a problem? Please describe.**
When generating messages, it can be benifitial to not have a forced `{user}:` prepended when using Pyg models. This is especially important when your goal is to continue from the previous message.

**Describe the solution you'd like**
`{user}:` would not be prepended when using Pyg formatting/Pyg models with `Always add character's name to prompt` disabled.

**Describe alternatives you've considered**
The main idea is to allow continuation of messages, so possibly a way to generate "more" off a previous message which could add the generation to the message itself.

**Comment by Necroxix** [comment]
This is something I'd love to see too. Like a button similar to the swype that would continue the generation further on that message for another, say, 30 tokens in instances where it got cut off because it was longer than your initial generation count parameter setting.

**Comment by cass02** [comment]
I appreciate the option! I tested it out and it works great! I will follow-up with one additional feature request to round everything up! -> https://github.com/Cohee1207/SillyTavern/issues/85#issue-1669725646

> This is something I'd love to see too. Like a button similar to the swype that would continue the generation further on that message for another, say, 30 tokens in instances where it got cut off because it was longer than your initial generation count parameter setting.

If someone wants to follow-up with that feature request, feel free. I'm going to close, as this completes the feature I requested as this works perfectly!

Thank you so much!
