### ISSUE TITLE
 [Feature Request]  Resizeable textarea's? Or make them bigger at least.

### ISSUE THREAD

**Issue by kakhulu31** [Cohee1207/SillyTavern#73]
Currently Description, Impersonation, Jailbreak, NSFW, Main, First message textarea's are too small for comfortable use (in my experience). Especially Description one. 
**Describe the solution you'd like**
If its possible I'd like to have them resizable. If not, increase the default size for the description field at least, since it doesn't  really affect anything negatively. 
![1681503109126256](https://user-images.githubusercontent.com/51547727/232145850-482be262-5023-4992-a575-716f5c6f5c9f.png)

**Comment by kakhulu31** [comment]
Firefox, pc.

**Comment by RossAscends** [comment]
The text areas are indeed resizable. However on Firefox the icon in the bottom right to indicate this is difficult to see. 

You can click the bottom edge to resize them.
