### ISSUE TITLE
[BUG] Mobile WaifuMode no longer works

### ISSUE THREAD

**Issue by TheWandering514** [Cohee1207/SillyTavern#95]
**Describe the bug**
Toggling on WaifuMode on mobile platform no longer works as expected as of a recent pull.

**To Reproduce**
Steps to reproduce the **bugged** behavior:
1. Pull the latest version of the Dev branch
2. Launch SillyTavern locally on Android Termux
3. Go to the SillyTavern site on mobile device and enable WaifuMode
4. Bug seen where WaifuMode does not work as expected

**EDIT 4:** Steps to reproduce the **expected** behaviour
1. Do git reset 3af6bca --hard
2. Launch SillyTavern locally on Android Termux
3. Go to the SillyTavern site on mobile device and enable WaifuMode
4. WaifuMode should work as expected

**Expected behavior**
Enabling WaifuMode should enable the layout to switch to the expected layout where the chat window becomes smaller, allowing both the background and character expression sprites to be seen. This had been working previously.

**Screenshots**

Screenshots taken from Android

WaifuMode disabled
![Screenshot_20230417_214351_com android chrome_edit_1465949120583080](https://user-images.githubusercontent.com/130191619/232609510-cfd9c145-3be2-4a74-9bb3-3be350bea2c0.jpg)

WaifuMode enabled (UI has rounded edges as expected, but chat window still covers the screen without being able to see the background nor character expression sprites)
![Screenshot_20230417_214400_com android chrome_edit_1465962332753391](https://user-images.githubusercontent.com/130191619/232609451-b8ac2a23-4735-4301-a96f-9824bc61b442.jpg)

**EDIT 3:** A screenshot of the expected behaviour when enabling WaifuMode on mobile devices, as seen when I did git reset to the working version I had. 
![Screenshot_20230418_061840_edit_1496659446834644](https://user-images.githubusercontent.com/130191619/232678398-b73d42da-89e5-40e1-83d9-2382ad08acb4.jpg)

**Desktop (please complete the following information):**
 - OS/Device: Android, iOS
 - Environment: Locally run SillyTavern on Android device, Cloud (Colab) run extensions
 - Browser: Chrome

 - Generation API: KoboldAI
 - Branch: dev
 - Model: Pygway 6b

**Additional context**
~~Mobile WaifuMode had been working for me around the time before a commit changing how stop_sequences was made, unfortunately I did not think to grab a screenshot of it working in action. https://github.com/Cohee1207/SillyTavern/commit/c5a3ec7d6ee07267b4bd8c72e3227977c78eb47c~~
~~**EDIT:** Another noteworthy feature of the old working version was that the offline expressions could only select 6 expressions, rather than 28 from the most recent pull.~~
~~The last pull I did before noticing this bug was after the character backgrounds plugin was implemented, although this commit specifically https://github.com/Cohee1207/SillyTavern/commit/3d1e0f3aa1be4b5362856588d0b127878dc799aa - perhaps a commit made between these two points might have broken mobile WaifuMode.~~ Disregard - see below edit.

**EDIT 2:** I did a git reset and found that this was the _exact_ point that I had when the mobile WaifuMode was still working. Also included a new screenshot showing the expected behaviour. https://github.com/Cohee1207/SillyTavern/commit/3af6bcafa77fe29c6e604cde9535a89f787ab3af

**Comment by RossAscends** [comment]
This has been fixed. Thanks for bringing it up!

**Comment by TheWandering514** [comment]
> This has been fixed. Thanks for bringing it up!

Thanks for the fix, although there's something that I've noticed: Wider sprites end up appearing much smaller than usual - reminds me a lot of when I was using expression sprites pre WaifuMode, when they were squished into the side of the chat window.

**Screenshot of current version:**
![Screenshot_20230418_141147_com android chrome_edit_1507855207561582](https://user-images.githubusercontent.com/130191619/232794081-cd8595bf-c41f-4d34-bacc-a019dad150e5.jpg)

**Screenshot of previous version:**
![Screenshot_20230418_141059_com android chrome_edit_1507841877298563](https://user-images.githubusercontent.com/130191619/232795161-ab795188-0d88-4b87-ae7a-8cbfac9654d3.jpg)


I wonder if it's possible to end up with something like the previous version, maybe without so much of an abrupt cut off at the edges of the sprite as a bonus?

**Comment by TheWandering514** [comment]
I just pulled the latest changes, and it looks great. Thank you once again! Definitely can put a close on this now.
![Screenshot_20230418_211126_com android chrome_edit_1528212994948059](https://user-images.githubusercontent.com/130191619/232894182-fd3f4b1f-d237-4279-9572-b75acb1e2844.jpg)
